### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by chrispopp8** [raspgot/Contact-Form-PHP#7]
I've downloaded the code and made it work... until I introduced checkboxes. Now it's choking. 

The error I am getting is:

`
PHP Warning:  Undefined array key "instype[]" in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 91
PHP Fatal error:  Uncaught TypeError: Ajax_Form::secure(): Argument #1 ($post) must be of type string, null given, called in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 91 and defined in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php:184
Stack trace:
#0 /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php(91): Ajax_Form->secure(NULL)
#1 /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php(207): Ajax_Form->__construct()
#2 {main}
  thrown in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 184
`

My code after I have edited it is:

```
PHP Warning:  Undefined array key "instype[]" in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 91
PHP Fatal error:  Uncaught TypeError: Ajax_Form::secure(): Argument #1 ($post) must be of type string, null given, called in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 91 and defined in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php:184
Stack trace:
#0 /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php(91): Ajax_Form->secure(NULL)
#1 /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php(207): Ajax_Form->__construct()
#2 {main}
  thrown in /home1/bluehqwi/public_html/gowithfm/quote/AjaxForm.php on line 184
```

The code I am using is:

```
<?php

/**
 * Simple and secure contact form using Ajax, validations inputs, SMTP protocol and Google reCAPTCHA v3 in PHP.
 * 
 * @see      https://github.com/raspgot/AjaxForm-PHPMailer-reCAPTCHA
 * @package  PHPMailer | reCAPTCHA v3
 * @author   Gauthier Witkowski <contact@raspgot.fr>
 * @link     https://raspgot.fr
 * @version  1.1.0
 */

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

# https://www.php.net/manual/timezones.php
date_default_timezone_set('America/Los_Angeles');

require __DIR__ . '/../PHPMailer/Exception.php';
require __DIR__ . '/../PHPMailer/PHPMailer.php';
require __DIR__ . '/../PHPMailer/SMTP.php';
require __DIR__ . '/../recaptcha/autoload.php';

class Ajax_Form {

    # Constants to redefined
    # Check this for more configurations: https://blog.mailtrap.io/phpmailer
    const HOST        = 'XXXXX'; # SMTP server
    const USERNAME    = 'XXXXX'; # SMTP username
    const PASSWORD    = 'XXXXX'; # SMTP password
    const SECRET_KEY  = 'XXXXX'; # GOOGLE secret key
    const SMTP_SECURE = PHPMailer::ENCRYPTION_STARTTLS;
    const SMTP_AUTH   = true;
    const PORT        = 587;
    const SUBJECT     = 'XXXXX';
    const HANDLER_MSG = [
        'success'       => '✔️ Your message has been sent !',
        'token-error'   => '❌ Error recaptcha token.',
        'enter_firstname'    => '❌ Please enter your first name.',
		'enter_lastname'    => '❌ Please enter your last name.',
        'enter_email'   => '❌ Please enter a valid email.',
		'enter_phone' => '❌ Please enter a valid phone number.',
        'enter_message' => '❌ Please enter your message.',
        'bad_ip'        => '❌ 56k ?',
        'ajax_only'     => '❌ Asynchronous anonymous.',
        'email_body'    => '
            <h1>{{subject}}</h1>
			<p><b>First name:</b> {{firstname}}</p>
			<p><b>Last name:</b> {{lastname}}</p>
			<p><b>Email:</b> {{email}}</p>
			<p><b>Phone:</b> {{phone}}</p>
			<p><b>Address 1:</b> {{address1}}</p>
			<p><b>Address 2:</b> {{address2}}</p>
			<p><b>City:</b> {{city}}</p>
			<p><b>State:</b> {{state}}</p>
			<p><b>Zip:</b> {{zip}}</p>
			<p><b>Interested in:</b> {{instype}}</p>
'
    ];
			
			/* <p><b>Date</b>: {{date}}</p>
            <p><b>Name</b>: {{name}}</p>
            <p><b>E-Mail</b>: {{email}}</p>
            <p><b>Message</b>: {{message}}</p>
            <p><b>IP</b>: {{ip}}</p>
        ' 
    ];*/

    /**
     * Ajax_Form constructor
     */
    public function __construct()
    {
        # Check if request is Ajax request
        if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] !== 'XMLHttpRequest') {
            $this->statusHandler('ajax_only');
        }

        # Check if fields has been entered and valid
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $firstname    = $this->secure($_POST['firstname']) ?? $this->statusHandler('enter_name');
			$lastname    = $this->secure($_POST['firstname']) ?? $this->statusHandler('enter_name');
            $email   = filter_var($this->secure($_POST['email']), FILTER_SANITIZE_EMAIL) ?? $this->statusHandler('enter_email');
            $phone = $this->secure($_POST['phone']) ?? $this->statusHandler('enter_phone');
			$address1 = $this->secure($_POST['address1']) ?? $this->statusHandler('enter_address1');
			$address2 = $this->secure($_POST['address2']) ?? $this->statusHandler('enter_address2');
			$city = $this->secure($_POST['city']) ?? $this->statusHandler('enter_city');
			$state = $this->secure($_POST['state']) ?? $this->statusHandler('enter_state');
			$zip = $this->secure($_POST['zip']) ?? $this->statusHandler('enter_zip');
			$instype = $this->secure($_POST['instype']) ?? $this->statusHandler('enter_instype');
			# $message = $this->secure($_POST['message']) ?? $this->statusHandler('enter_message');
            $token   = $this->secure($_POST['recaptcha-token']) ?? $this->statusHandler('token-error');
            $ip      = filter_var($_SERVER['REMOTE_ADDR'], FILTER_VALIDATE_IP) ?? $this->statusHandler('bad_ip');
            $date    = new DateTime();
        }

        # Prepare email body
        $email_body = self::HANDLER_MSG['email_body'];
        $email_body = $this->template($email_body, [
            'subject' => self::SUBJECT,
            'date'    => $date->format('j/m/Y H:i:s'),
            'firstname' => $firstname,
			'lastname' => $lastname,
			'email' => $email,
			'phone' => $phone,
			'address1' => $address1,
			'address2' => $address2,
			'city' => $city,
			'state' => $state,
			'zip' => $zip,
			'instype' => $instype
        ]);

        # Verifying the user's response
        $recaptcha = new \ReCaptcha\ReCaptcha(self::SECRET_KEY);
        $resp = $recaptcha
            ->setExpectedHostname($_SERVER['SERVER_NAME'])
            ->verify($token, $_SERVER['REMOTE_ADDR']);
            
        if ($resp->isSuccess()) {
            # Instanciation of PHPMailer
            $mail = new PHPMailer(true);
            $mail->setLanguage('en', __DIR__ . '/vendor/PHPMailer/language/');

            try {
                # Server settings
                $mail->SMTPDebug  = SMTP::DEBUG_OFF;   # Enable verbose debug output
                $mail->isSMTP();                       # Set mailer to use SMTP
                $mail->Host       = self::HOST;        # Specify main and backup SMTP servers
                $mail->SMTPAuth   = self::SMTP_AUTH;   # Enable SMTP authentication
                $mail->Username   = self::USERNAME;    # SMTP username
                $mail->Password   = self::PASSWORD;    # SMTP password
                $mail->SMTPSecure = self::SMTP_SECURE; # Enable TLS encryption, `ssl` also accepted
                $mail->Port       = self::PORT;        # TCP port

                # Recipients
                $mail->setFrom(self::USERNAME, $firstname, $lastname);
                $mail->addAddress($email, $firstname, $lastname);
                $mail->AddCC(self::USERNAME, 'Dev_copy');
                $mail->addReplyTo(self::USERNAME, 'Information');

                # Content
                $mail->isHTML(true);
                $mail->CharSet = 'UTF-8';
                $mail->Subject = self::SUBJECT;
                $mail->Body    = $email_body;
                $mail->AltBody = strip_tags($email_body);

                # Send email
                $mail->send();
                $this->statusHandler('success');

            } catch (Exception $e) {
                die(json_encode($mail->ErrorInfo));
            }
        } else {
            die(json_encode($resp->getErrorCodes()));
        }
    }

    /**
     * Template string values
     *
     * @param string $string
     * @param array $vars
     * @return string
     */
    public function template(string $string, array $vars): string
    {
        foreach ($vars as $name => $val) {
            $string = str_replace("{{{$name}}}", $val, $string);
        }

        return $string;
    }

    /**
     * Secure inputs fields
     *
     * @param string $post
     * @return string
     */
    public function secure(string $post): string
    {
        $post = htmlspecialchars($post, ENT_QUOTES);
        $post = stripslashes($post);
        $post = trim($post);

        return $post;
    }

    /**
     * Error or success message
     *
     * @param string $message
     * @return json
     */
    public function statusHandler(string $message): json
    {
        die(json_encode(self::HANDLER_MSG[$message]));
    }

}

# Instanciation 
new Ajax_Form();


```

I'll be the first to admit I'm not that great at PHP. 

How can I use checkboxes in my form with your script? 

(Note: I replaced my SMTP and reCaptcha info with XXXXX for security reasons in this post)

Thanks

**Comment by raspgot** [comment]
Hello,
You can try to replace this line:
```php
$instype = $this->secure($_POST['instype']) ?? $this->statusHandler('enter_instype');
```

By this line:
```php
if (!empty($_POST['instype']))
    $instype = $this->secure($_POST['instype']);
else
    $this->statusHandler('enter_instype');
```

And add a constant enter_instype in HANDLER_MSG array
```php
const HANDLER_MSG = [
    'enter_instype' => '❌ Please enter instype.'
];
```

In addition you can add a rules for "instype" field in the validate js
```js
$("#contactform").validate({
    // Form fields rules
    rules: {
        instype: {
            required: true
        }
    }
});
```
